project:
  type: website
  output-dir: docs 
  render:
    - "*.qmd"

execute:
  echo: false

website:
  title: "SISMID: Human-AI Teaming"
  navbar:
    left:
      - href: Overview.qmd
        text: Overview
      - href: about.qmd
        text: Preparation
      - href: additionaDetails.qmd
        text: Additional Resources
      - href: day1.qmd
        text: Day 1 Materials

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

